routes/web.php
<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\ColorController;
use App\Models\Student;
use Illuminate\Support\Facades\Route;
use SebastianBergmann\CodeCoverage\Report\Html\Dashboard;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

require __DIR__.'/auth.php';


Route::get('/', function () {
    return view('welcome');
});

// authentication
// Route::get('/dashboard', function () {
//     return view('dashboard');
// })->middleware(['auth', 'verified'])->name('dashboard');


Route::get('/dashboard',[AdminController::class,'dashboard'])->name('dashboard');

Route::get('/categories/pdf', [CategoryController::class, 'downloadPdf'])->name('categories.pdf');

Route::get('/products/pdf', [CategoryController::class, 'downloadPdf'])->name('products.pdf');



// Resoursce Route
Route::resource('categories', CategoryController::class);
Route::resource('products', ProductController::class);

Route::get('/categories-trash', [CategoryController::class, 'trash'])->name('categories.trash');
Route::get('/categories/{id}/restore', [CategoryController::class, 'restore'])->name('categories.restore');
Route::delete('/categories/{id}/delete', [CategoryController::class, 'delete'])->name('categories.delete');

Route::get('/products-trash', [CategoryController::class, 'trash'])->name('products.trash');
Route::get('/products/{id}/restore', [CategoryController::class, 'restore'])->name('products.restore');
Route::delete('/products/{id}/delete', [CategoryController::class, 'delete'])->name('products.delete');

//              ******** color route **********



Route::get('/colors-trash', [ColorController::class, 'trash'])->name('colors.trash');
Route::get('/colors/{id}/restore', [ColorController::class, 'restore'])->name('colors.restore');
Route::delete('/colors/{id}/delete', [ColorController::class, 'delete'])->name('colors.delete');
Route::get('/colors/pdf', [ColorController::class, 'downloadPdf'])->name('colors.pdf');
Route::resource('colors', ColorController::class);


//                  ******categories all route start *********

// Route::get('/categories',[CategoryController::class,'index'])->name('categories.index');
// Route::get('/categories/create',[CategoryController::class,'create'])->name('categories.create');
// Route::post('/categories',[CategoryController::class,'store'])->name('categories.store');
// Route::get('/categories/{id}',[CategoryController::class,'show'])->name('categories.show') ;
// Route::delete('/categories/{id}',[CategoryController::class,'destroy'])->name('categories.destroy');
// Route::get('/categories/{id}/edit',[CategoryController::class,'edit'])->name('categories.edit');
// Route::patch('/categories/{id}',[CategoryController::class,'update'])->name('categories.update');




//                  ************ Student Route Start **********
Route::get('/students/create',[StudentController::class,'create'])->name('students.create');
Route::post('/students',[StudentController::class,'store'])->name('students.store');
Route::get('/students/{id}/edit',[StudentController::class,'edit'])->name('students.edit');
Route::patch('/students/{id}',[StudentController::class,'update'])->name('students.update');

// agei krse
Route::get('/students',[StudentController::class,'index'])->name('students.index');
Route::get('/students/{id}',[StudentController::class,'show'])->name('students.show');
Route::delete('/students/{id}',[StudentController::class,'destroy'])->name('students.destroy');



Route::fallback(function () {
    echo('route thik moto den mia');
});

app/Models/Color.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Color extends Model
{
    use HasFactory;

    protected $guarded = [];


    // public function products()
    // {
    //     return $this->belongsToMany(Product::class);
    // }

}

app/Http/Controllers/ColorController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ColorRequest;
use App\Models\Color;
use Barryvdh\DomPDF\Facade\Pdf;
use Illuminate\Database\QueryException;

class ColorController extends Controller
{

    public function index()
    {
        $colors = Color::all();
        return view('admin.colors.index', compact('colors'));
    }

    public function create()
    {
        return view('admin.colors.create');
    }

    public function show(Color $color)
    {
        // $color = Color::find($id);
        return view('admin.colors.show', compact('Color'));
    }

    public function store(ColorRequest $request)
    {
        $requestData = [
            'title' => $request->title,
            'color_code' => $request->color_code,
        ];

        Color::create($requestData);

        return redirect()
            ->route('colors.index')
            ->withMessage('Successfully Created');
    }

    public function edit(Color $color)
    {
        // $color = Color::find($id);
        return view('admin.colors.edit', compact('color'));
    }

    public function update(ColorRequest $request, Color $color)
    {
        // $color = Color::find($id);

        $requestData = [
            'title' => $request->title,
            'color_code' => $request->color_code,
        ];

        $color->update($requestData);

        return redirect()
            ->route('colors.index')
            ->withMessage('Successfully Updated');
    }

    public function downloadPdf()
    {
        $colors = Color::all();
        $pdf = Pdf::loadView('colors.pdf', compact('colors'));
        return $pdf->download('Color-list.pdf');
    }

    public function destroy(Color $color)
    {
        // $color = Color::find($id);
        $color->delete();

        // Session::flash('message', 'Successfully deleted');
        // return redirect()
        //         ->route('colors.index')
        //         ->with('message', 'Successfully deleted');

        return redirect()
            ->route('colors.index')
            ->withMessage('Successfully deleted');
    }

    public function trash()
    {
        $colors = Color::onlyTrashed()->get();
        return view('admin.colors.trash', compact('colors'));
    }

    public function restore($id)
    {
        $color = Color::onlyTrashed()->find($id);
        $color->restore();

        return redirect()
            ->route('colors.trash')
            ->withMessage('Successfully restored');
    }

    public function delete($id)
    {
        try {
            $color = Color::onlyTrashed()->find($id);
            $color->forceDelete();

            return redirect()
                ->route('colors.trash')
                ->withMessage('Successfully deleted');
        } catch (QueryException $e) {
            return redirect()->back()->withErrors($e->getMessage());
        }
    }
}

resources/views/admin/colors/create.blade.php
<x-admin.master>
    <x-slot:title>
        Color Create
        </x-slot>
        <main class="main" id="main">
            @if (session('message'))
                <span class="text-success">{{ session('message') }}</span>
            @endif

            <div
                class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                <h1 class="h2">Colors</h1>
                <div class="btn-toolbar mb-2 mb-md-0">
                    <a href="{{ route('colors.index') }}">
                        <button type="button" class="btn btn-sm btn-outline-info">
                            <span data-feather="list"></span>
                            List
                        </button>
                    </a>
                </div>
            </div>

            <x-forms.errors />

            <form action="{{ route('colors.store') }}" method="post">
                @csrf

                <x-forms.input type="text" name="title" placeholder="Enter title" required label="Title" />

                <x-forms.input type="color" name="color_code" required label="Color Code" />

                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </main>
</x-admin.master>

resources/views/admin/colors/edit.blade.php
<x-admin.master>
    <x-slot:title>
        Category Create
        </x-slot>
        <main class="main" id="main">

        @if(session('message'))
        <span class="text-success">{{ session('message') }}</span>
        @endif

        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">Categories</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
                <a href="{{ route('categories.index') }}">
                    <button type="button" class="btn btn-sm btn-outline-info">
                        <span data-feather="list"></span>
                        List
                    </button>
                </a>
            </div>
        </div>

        <x-forms.errors />

        <form action="{{ route('categories.update', $category->id) }}" method="post" enctype="multipart/form-data">
            @csrf
            @method('patch')

            <x-forms.input
                type="text"
                name="title"
                :value="old('title', $category->title)"
                placeholder="Enter title"
                required
            />

            <img src="{{ asset('storage/categories/'.$category->image) }}" height="250" />

            <x-forms.input type="file" name="image" label='Picture' />

            @php
                $checklist = ['Is Active ?'];

                if($category->is_active){
                    $checkedItems = [0];
                } else {
                    $checkedItems = [];
                }
            @endphp

            <x-forms.checkbox :checklist="$checklist" :checkedItems="$checkedItems" />

            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
        </main>
</x-admin.master>

resources/views/admin/colors/index.blade.php
<x-admin.master>
    <x-slot:title>
        Color List
        </x-slot>
        <main class="main" id="main">
            <x-forms.message />
            <div
                class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                <h1 class="h2">Colors</h1>
                <div class="btn-toolbar mb-2 mb-md-0">
                    <div class="btn-group me-2">
                        <a href="{{ route('colors.pdf') }}">
                            <button type="button" class="btn btn-sm btn-outline-secondary">PDF</button>
                        </a>
                        <button type="button" class="btn btn-sm btn-outline-secondary">Excel</button>
                        <a href="{{ route('colors.trash') }}">
                            <button type="button" class="btn btn-sm btn-outline-danger">Trash</button>
                        </a>
                    </div>
                    <a href="{{ route('colors.create') }}">
                        <button type="button" class="btn btn-sm btn-outline-primary">
                            <span data-feather="plus"></span>
                            Add New
                        </button>
                    </a>
                </div>
            </div>

            <table class="table">
                <thead>
                    <tr>
                        <th>SL#</th>
                        <th>Title</th>
                        <th>Color</th>
                        <th width="180">Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($colors as $color)
                        <tr>
                            <td>{{ $loop->iteration }}</td>
                            <td>{{ $color->title }}</td>
                            <td>
                                <div style="background-color: {{ $color->color_code }}">{{ $color->color_code }}</div>
                            </td>

                            <td>
                                <a class="btn btn-sm btn-info" href="{{ route('colors.show', $color->id) }}">Show</a>
                                <a class="btn btn-sm btn-warning" href="{{ route('colors.edit', $color->id) }}">Edit</a>
                                <form action="{{ route('colors.destroy', $color->id) }}" method="post"
                                    style="display:inline">
                                    @csrf
                                    @method('delete')
                                    <button class="btn btn-sm btn-danger"
                                        onclick="return confirm('Are you sure want to delete')">Delete</button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </main>
</x-admin.master>

resources/views/admin/colors/pdf.blade.php
<table>
    <thead>
        <tr>
            <th>SL#</th>
            <th>Title</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach($categories as $category)
        <tr>
            <td>{{ $loop->iteration }}</td>
            <td>{{ $category->title }}</td>
        </tr>
        @endforeach
    </tbody>
</table>

resources/views/admin/colors/show.blade.php
<x-admin.master>
    <x-slot:title>
        Category Details
        </x-slot>
        <main class="main" id="main">
            <div
                class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                <h1 class="h2">Categories</h1>
                <div class="btn-toolbar mb-2 mb-md-0">
                    <a href="{{ route('categories.index') }}">
                        <button type="button" class="btn btn-sm btn-outline-primary">
                            <span data-feather="list"></span>
                            List
                        </button>
                    </a>
                </div>
            </div>

            <h1>Title: {{ $category->title }}</h1>

            <img src="{{ asset('storage/categories/' . $category->image) }}" />

            <p>Is Active ?: {{ $category->is_active ? 'Yes' : 'No' }}</p>

            <h1>Products</h1>
            <hr>
            <table class="table">
                <thead>
                    <tr>
                        <th>SL#</th>
                        <th>Title</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($category->products as $product)
                        <tr>
                            <td>{{ $loop->iteration }}</td>
                            <td>{{ $product->title }}</td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </main>
</x-admin.master>

resources/views/admin/colors/trash.blade.php
<x-admin.master>
    <x-slot:title>
        {{ __('Category List') }}
        </x-slot>
        <main class="main" id="main">
            <x-forms.message />
            <x-forms.errors />

            <div
                class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                <h1 class="h2">{{ __('Categories Trash') }}</h1>
                <div class="btn-toolbar mb-2 mb-md-0">
                    <a href="{{ route('categories.index') }}">
                        <button type="button" class="btn btn-sm btn-outline-primary">
                            <span data-feather="list"></span>
                            {{ __('List') }}
                        </button>
                    </a>
                </div>
            </div>

            <table class="table">
                <thead>
                    <tr>
                        <th>{{ __('SL#') }}</th>
                        <th>{{ __('Title') }}</th>
                        <th>{{ __('Action') }}</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($categories as $category)
                        <tr>
                            <td>{{ $loop->iteration }}</td>
                            <td>{{ $category->title }}</td>
                            <td>
                                <a class="btn btn-sm btn-info"
                                    href="{{ route('categories.show', $category->id) }}">Show</a>
                                <a class="btn btn-sm btn-warning"
                                    href="{{ route('categories.restore', $category->id) }}">Restore</a>
                                <form action="{{ route('categories.delete', $category->id) }}" method="post"
                                    style="display:inline">
                                    @csrf
                                    @method('delete')
                                    <button class="btn btn-sm btn-danger"
                                        onclick="return confirm('Are you sure want to delete')"
                                        title="Permanent Delete">Delete</button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
            <main class="main" id="main">
</x-admin.master>